[versions]
jvm-target = "21"
kotlin-coroutines = "1.6.1"
ecwid-consul-api = "1.4.5"
arrow = "1.2.0-RC"
otel-spring = "1.31.0-alpha"
auth0-java-jwt = "4.4.0"
junit-jupiter = "5.10.3"
mockwebserver = "4.12.0"
junit-platform-suite = "1.10.2"
cucumber = "7.18.1"
testcontainers = "1.20.3"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }

jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

ecwid-consul-api = { module = "com.ecwid.consul:consul-api", version.ref = "ecwid-consul-api" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
auth0-java-jwt = { module = "com.auth0:java-jwt", version.ref = "auth0-java-jwt" }

otel-api = { module = "io.opentelemetry:opentelemetry-api" }
otel-sdk = { module = "io.opentelemetry:opentelemetry-sdk" }
otel-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
otel-extension-kotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin" }
otel-spring = { module = "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter", version.ref = "otel-spring" }

# Test libraries
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter"  }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform-suite" }

mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver"}

cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
